//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collection_Request()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Status { get; set; }
        public string Food_Details { get; set; }
        public int Quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
